services:
  api-service:
    container_name: api-container-1
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    networks:
      - backend

networks:
  backend:
    driver: bridge