spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/testdb}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:050698}
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
      show-sql: false
      hibernate:
        ddl-auto: none
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: api-service
    server: http://localhost:${server.port}
    title: API Document
    version: 1.0.0